src/assets/icon.ts, src/assets/icon/common/navigation_bar/add_btn.svg, src/assets/icon/vote/add_vote_btn.svg, src/components/Header/Header.tsx, src/components/Header/Styles.ts, src/components/navigationbar/NavigationBar.tsx, src/components/navigationbar/Styles.ts
closed #5 
- 화면의 하단 중앙에 고정되도록 position 설정
- 상단에 고정되도록 position 설정
- 파라미터로 헤더에 배치할 아이콘을 선택할 수 있도록 구현
- backarrow, check, hamburger, addbtn 중에 파라미터를 골라서 헤더에 아이콘을 배치한다
- 사용 예)
=> feat: 하단 네비게이션바 및 헤더 퍼블리싱

src/App.tsx, src/components/ShareGroup/ShareGroupListItem/Styles.ts, src/components/ShareGroup/ShareGroupListView/Styles.ts, src/pages/ShareGroupMain/ShareGroupMain.tsx, src/styles/colors.ts
#7
colors.ts 파일의 Color Scheme를 사용하기 위해 App.tsx에 ThemeProvider를 추가했습니다.
사용법: ${({ theme }) => theme.colors.primary}
=> Style: ThemeProvider 추가

src/App.tsx, src/components/MyPage/MyPage.tsx, src/components/MyPage/Styles.ts
=> feat : MyPage 컴포넌트

src/App.tsx, src/components/Notice/GroupNotice/GroupNotice.tsx, src/components/Notice/GroupNotice/Styles.ts, src/components/Notice/Notice.tsx, src/components/Notice/Styles.ts
#14 
closed #14
Notice 컴포넌트 퍼블리싱
=> feat : Notice 퍼블리싱

src/App.tsx, src/components/AddGroup/AddGroupHeadCount/HeadCount.tsx, src/components/AddGroup/AddGroupHeadCount/Styles.ts, src/components/AddGroup/AddGroupLoading/AddGrouploading.tsx, src/components/AddGroup/AddGroupLoading/Styles.ts, src/components/AddGroup/AddGroupMembername/AddGroupMembername.tsx, src/components/AddGroup/AddGroupMembername/Styles.ts, src/components/AddGroup/AddGroupShare/Styles.ts, src/components/AddGroup/AddGroupSpace/Space.tsx, src/components/AddGroup/AddGroupType/GroupType.tsx, src/components/AddGroup/AddGroupType/Styles.ts, src/pages/ShareGroupMain/ShareGroupMain.tsx
=> Feat/#11 addgroup 라우팅 완료

src/pages/EnterMain/EnterClause/EnterClause.tsx, src/pages/EnterMain/EnterLogin/EnterLogin.tsx, src/pages/EnterMain/EnterLogin/Styles.ts
=> feat : enter페이지 로그인

package-lock.json, package.json, src/App.tsx, src/components/AddGroup/AddGroupHeadCount/HeadCount.tsx, src/components/AddGroup/AddGroupHeadCount/Styles.ts, src/components/AddGroup/AddGroupLoading/AddGrouploading.tsx, src/components/AddGroup/AddGroupLoading/Styles.ts, src/components/AddGroup/AddGroupMembername/AddGroupMembername.tsx, src/components/AddGroup/AddGroupMembername/Styles.ts, src/components/AddGroup/AddGroupShare/Styles.ts, src/components/AddGroup/AddGroupSpace/Space.tsx, src/components/AddGroup/AddGroupType/GroupType.tsx, src/components/AddGroup/AddGroupType/Styles.ts, src/components/Notice/GroupNotice/GroupNotice.tsx, src/styles/GlobalStyles.ts
Reverts Na-o-man/Na-o-man_Web#46
=> Revert "Feat/11"

src/components/Notice/GroupNotice/GroupNotice.tsx, src/components/Notice/GroupNotice/Styles.ts, src/components/Notice/Notice.tsx, src/components/Notice/Styles.ts
#32 
closed #32 
notice 버튼 이벤트 구현
=> feat : notice 버튼 이벤트 구현

src/apis/getNotice.ts, src/components/Notice/GroupNotice/Styles.ts, src/components/Notice/Notice.tsx, src/components/Notice/Styles.ts, src/recoil/states/notice.ts, src/recoil/types/notice.ts
#45 
closed #45 
notification api 구현
=>  feat : notification post, get api 구현

src/App.tsx, src/apis/getMembers.ts, src/pages/Notice/Notice.tsx, src/recoil/types/members.ts
<!-- 관련있는 이슈 번호(#000)을 적어주세요.
#57 
notice 페이지 추가
회원 가입 여부 조회, 마켓팅 약관 동의 여부 조회 api 추가
=> feat : notice 페이지 및 api 추가

src/apis/getNotice.ts, src/components/AddGroup/AddGroupType/MemberTypeList/MemberTypeList.tsx, src/components/Notice/GroupNotice/GroupNotice.tsx, src/components/Notice/Notice.tsx
#48
notification delete api구현
-특정 알림 삭제 ->함수만 작성
-모든 알림 삭제
=> feat: notification delete api구현

src/apis/getMembers.ts, src/components/MyPage/Modal/Modal.tsx, src/components/MyPage/Modal/Styles.ts, src/components/MyPage/MyPageMain.tsx, src/pages/MyPage/MyPage.tsx, src/recoil/states/mypage.ts, src/recoil/types/members.ts
#57
closed #57 
회원 탈퇴 api 추가 및 modal 수정
=> feat : 회원 탈퇴 api 추가 및 modal 수정

package-lock.json, package.json, src/App.tsx, src/components/AddGroup/AddGroupLoading/AddGrouploading.tsx, src/components/AddGroup/AddGroupShare/AddGroupshare.tsx, src/components/AddGroup/AddGroupShare/Styles.ts, src/components/AddGroup/AddGroupSpace/Space.tsx, src/components/AddGroup/state.tsx, src/components/join_group/group3_styles.ts, src/components/join_group/join_group_1.tsx, src/components/join_group/join_group_2.tsx, src/components/join_group/join_group_3.tsx, src/components/join_group/picture.tsx, src/components/join_group/profile.tsx, src/index.tsx, src/pages/EnterMain/EnterLogin/EnterLogin.tsx, src/recoil/states/share_group.ts
closed #55 
공유 그룹 생성 ,조회 ,참여 api 구현하였습니다. 
생성과 조회는 정상 작동하는 것을 test 하였으나 , 참여는 member들의 profie이 만들어진 후 test 해봐야할 거 같습니다
=> Feat: 공유그룹 생성 , 조회 , 참여 api 조회 

src/apis/getPhotosAll.ts, src/apis/postPhotoUpload.ts, src/apis/postPresignedUrl.ts, src/components/Header/Header.tsx, src/components/ShareGroup/ShareGroupCloudButton/ShareGroupCloudButton.tsx, src/components/navigationbar/NavigationBar.tsx, src/components/navigationbar/Styles.ts, src/pages/EnterMain/EnterClause/EnterClause.tsx
=> Feat/#62 사진 업로드 api 구현

src/components/MainScreen.tsx, src/components/MyPage/Modal/Modal.tsx
<!-- 관련있는 이슈 번호(#000)을 적어주세요.
#70 
미디어 쿼리 적용
로그아웃 기능 구현
=> feat : 미디어 쿼리 적용 및 로그아웃 기능 구현

src/App.tsx, src/apis/getPhotos.ts, src/components/ShareGroup/ShareGroupCarouselItem/ShareGroupCarouselItem.tsx, src/pages/ShareGroup/ShareGroupDetailPage/DropDown.tsx, src/pages/ShareGroup/ShareGroupDetailPage/ShareGroupDetailPage.tsx, src/pages/ShareGroup/ShareGroupDetailPage/Styles.ts, src/pages/ShareGroup/ShareGroupFolder/ShareGroupFolder.tsx, src/recoil/states/share_group.ts
=> Feat/#62 특정 앨범 조회 api 연동 완료

package-lock.json, src/components/AddGroup/AddGroupShare/AddGroupshare.tsx, src/components/AddGroup/AddGroupShare/Styles.ts, src/components/Vote/VoteList/VoteList.tsx, src/components/join_group/join_group_2.tsx, src/components/join_group/join_group_3.tsx, src/components/join_group/profile.tsx, src/pages/EnterMain/EnterMain.tsx
=> Feat: 공유그룹 참여 api 재구현

src/apis/deleteAgenda.ts, src/components/Vote/VoteList/VoteList.tsx, src/recoil/states/vote.ts
=> feat : Agenda delete api 함수 작성

src/apis/getAgendaDetail.ts, src/components/Vote/VoteModal/VoteResultModal.tsx, src/recoil/types/vote.ts
#70 
closed#70 
특정 안건 상세 조회 api 구현
=> feat : 안건 상세 조회 api 구현

src/apis/deletePhoto.ts, src/components/ShareGroup/ShareGroupBottomBar/ShareGroupBottomBar.tsx, src/components/ShareGroup/ShareGroupBottomBar/Styles.ts, src/components/ShareGroup/ShareGroupImageList/ShareGroupImageList.tsx, src/pages/ShareGroup/ShareGroupDetailPage/ShareGroupDetailPage.tsx
#81 
closed #81 
사진 삭제 기능 구현
사진 삭제 기능입니다!
(로컬에서만 삭제하는거라 새로고침하면 여전히 사진이 남아있습니다)
=> feat : 사진 삭제 기능 구현

src/components/Common/DropDown/DropDown.tsx, src/components/Vote/VoteContainer/VoteContainer.tsx, src/components/Vote/VoteList/VoteList.tsx, src/pages/Vote/VoteDetailPage/VoteDetailPage.tsx, src/pages/Vote/VotePage/VotePage.tsx, src/recoil/selectors/vote.ts, src/recoil/states/share_group.ts, src/recoil/states/vote.ts, src/recoil/types/vote.ts
=> [Feat] 안건조회 api 구현 

src/components/Vote/VoteContainer/Styles.ts, src/components/Vote/VoteList/Styles.ts, src/components/Vote/VoteList/VoteList.tsx, src/pages/Vote/VoteListPage/Styles.ts
#87 
스와이프 방식 -> 무한스크롤로 변경 
안건 조회 페이지 피드백 디자인으로 변경
만일 드롭다운에서 안건이 없는 ShareGroupId 선택시 ,/vote 페이지로 이동하여서 다시 안건이 있는 ShareGroupId를 택해도 안건이 뜨지 않음 수정이 필요해보임
=> Feat: 안건 조회 디자인 수정 ,무한스크롤로 변경

src/components/ShareGroup/ShareGroupBottomBar/ShareGroupBottomBar.tsx, src/components/ShareGroup/ShareGroupCarousel/Styles.ts, src/components/ShareGroup/ShareGroupFolderView/Styles.ts, src/components/ShareGroup/ShareGroupImageList/ShareGroupImageList.tsx, src/components/ShareGroup/ShareGroupImageList/Styles.ts, src/components/ShareGroup/ShareGroupTopButton/Styles.ts, src/pages/ShareGroup/ShareGroupDetailPage/ShareGroupDetailPage.tsx, src/utils/ImageZipDownloader.ts
#89 
- 개별 사진 다운로드 구현
- 무한스크롤 구현
- 다운로드 시 모바일 환경에서 갤러리로 다운로드. 아니면 zip으로 압축해서 다운로드함
- 공유그룹 상세 페이지(폴더)에서 상단 제목의 위치 수정
=> Feat: 개별 사진 다운로드 구현 등 3개

src/apis/getMembers.ts, src/assets/icon.ts, src/assets/icon/enter/icon_check4.svg, src/components/MyPage/Modal/Modal.tsx, src/components/MyPage/Styles.ts, src/pages/EnterMain/EnterClause/EnterClause.tsx, src/pages/EnterMain/EnterClause/Styles.ts, src/pages/EnterMain/EnterPhoto/Styles.ts, src/recoil/types/members.ts
=> feat : 회원 탈퇴 api 수정 및 디자인 수정

src/components/Notice/GroupNotice/GroupNotice.tsx, src/components/Notice/GroupNotice/Styles.ts, src/components/Notice/Notice.tsx, src/components/Notice/Styles.ts, src/recoil/types/notice.ts
데이터 추가 및 왼쪽 프로필에 본인 프로필이 뜨도록 수정했습니다!
=> Docs : notice 데이터 추가 및 수정

src/components/Vote/VoteList/VoteList.tsx
=> feat:안건 목록 조회 url 수정

src/components/AddGroup/AddGroupMembername/membernameList/Styles.ts, src/components/AddGroup/AddGroupMembername/membernameList/membernameList.tsx
=> feat: addgroup 디자인 수정

src/components/AddGroup/AddGroupMembername/Styles.ts, src/components/AddGroup/AddGroupMembername/membernameList/Styles.ts, src/components/AddGroup/AddGroupMembername/membernameList/membernameList.tsx
=> feat: addgroup 수정

src/components/join_group/group2_styles.ts, src/components/join_group/join_group_3.tsx
#100 
null인 값만 뜨는 함수는 회원가입이 되지 않아 테스트 하지 못함 -> 테스트 필요
=>  feat: join group 디자인 수정, memberId null만 뜨도록 하는 필터 함수 구현

src/apis/getMyShareGroup.ts, src/apis/getPhotosDownload.ts, src/components/Common/DropDown/DropDown.tsx, src/components/MainScreen.tsx, src/components/ShareGroup/ShareGroupBottomBar/ShareGroupBottomBar.tsx, src/components/ShareGroup/ShareGroupCarousel/ShareGroupCarousel.tsx, src/components/ShareGroup/ShareGroupCarouselItem/ShareGroupCarouselItem.tsx, src/components/ShareGroup/ShareGroupImageList/ShareGroupImageList.tsx, src/components/ShareGroup/ShareGroupTopButton/ShareGroupTopButton.tsx, src/components/Vote/PhotoContainer/PhotoContainer.tsx, src/components/Vote/VoteInput/VoteInput.tsx, src/components/Vote/VoteList/VoteList.tsx, src/pages/ShareGroup/ShareGroupFolder/ShareGroupFolder.tsx, src/pages/ShareGroup/ShareGroupMain/ShareGroupMain.tsx, src/pages/Vote/EmptyVotePage/EmptyVotePage.tsx, src/pages/Vote/VoteDetailPage/VoteDetailPage.tsx, src/pages/Vote/VoteMainPage.tsx, src/pages/Vote/VotePage/VotePage.tsx, src/recoil/states/vote.ts
=> Fix/#105 다운로드

src/utils/ImageZipDownloader.ts
=> Fix: 다운로드 로직 변경

src/components/MainScreen.tsx, src/components/Vote/PhotoContainer/PhotoAddBtn.tsx, src/pages/ShareGroup/ShareGroupDetailPage/ShareGroupDetailPage.tsx, src/utils/ImageZipDownloader.ts
=> Fix: 비율 수정
